#ifndef STRING_CONSTANTS_H
#define STRING_CONSTANTS_H

#define TEXT_MAIN_TITLE  "main_title"
#define TEXT_HELP        "help"
#define TEXT_NEW_GAME    "new_game"
#define TEXT_LOAD_LEVEL  "load_level"
#define TEXT_OPTIONS     "options"
#define TEXT_EXIT        "exit"
#define TEXT_BACK        "back"
#define TEXT_HINT_MOVE   "hint_move"
#define TEXT_HINT_ENTER  "hint_enter"
#define TEXT_DEV_NOTE    "developer_note"
#define TEXT_INSTR_1     "instructions_1"
#define TEXT_INSTR_2     "instructions_2"
#define TEXT_INSTR_3     "instructions_3"
#define TEXT_LEVEL       "level"
#define TEXT_PAUSE       "pause"
#define TEXT_RESUME      "resume"
#define TEXT_SOUND       "sound"
#define TEXT_LANGUAGE    "language"
#define TEXT_SPANISH     "spanish"
#define TEXT_ENGLISH     "english"
#define TEXT_ON          "on"
#define TEXT_OFF         "off"
#define TEXT_LOCKED      "locked"
#define TEXT_GAME_OVER   "game_over"
#define TEXT_RETRY       "retry"
#define TEXT_LIFE        "life"
#define TEXT_SCORE       "score"
#define TEXT_CONTINUE    "next_level"
#define TEXT_COMPLETED   "level_completed"

#endif /* STRING_CONSTANTS_H */
